spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: order_user
    password: order_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: order-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.saga.orderservice.event"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.saga.orderservice.event.StockReservationResult

server:
  port: 8081

inventory-service:
  base-url: http://localhost:8082